### ISSUE TITLE
Preliminary review rejection - calling remote script is unsecure.

### ISSUE THREAD

**Issue by JamesABaker** [jbkr/Firefox-mendeley#1]
This might be a problem... Needs local copies of Mendeley's scripts to be accepted by Mozilla.

```
     Your add-on, Unofficial Mendeley Importer 0.0.1, has been reviewed by an editor and did not meet the criteria for being hosted in our gallery.

    Comments:
    Your version was rejected because of the following problems:

    1) We don't allow add-ons to use remote scripts because they create serious security vulnerabilities. We also need to review all of your add-on code, and this makes it much more difficult. Please insert those scripts locally from your add-on code.

    data/call.js
    data/mendeleybookmarksource.js

    Please fix them and submit again. Thank you.



    This version of your add-on has been disabled. You may re-request review by addressing the editor's comments and uploading a new version. To learn more about the review process, please visit https://addons.mozilla.org/developers/docs/policies/reviews

    If you have any questions or comments on this review, please reply to this email or join #amo-editors on irc.mozilla.org
```

**Comment by JamesABaker** [comment]
The latest issue is that as of Firefox v48, there is no way of running an unsigned addon in Firefox. Only developer versions continue support for installing the unsigned addons after changing the **about:config** preference from `xpinstall.signatures.required True` to `xpinstall.signatures.required False`

**Comment by jbkr** [comment]
Add on now signed by Mozilla. Preliminary review passed and valid as an unlisted add-on.

<img width="969" alt="screen shot 2016-08-16 at 17 17 10" src="https://cloud.githubusercontent.com/assets/6866798/17694202/51546a60-63d5-11e6-88b6-2cc683adebab.png">

**Comment by JamesABaker** [comment]
> Hello,
> 
> Your add-on, Unofficial Mendeley Importer 0.0.1, has passed our automatic tests and is now signed and ready for you to download at https://addons.mozilla.org/en-GB/developers/addon/unofficial-mendeley-importer/versions
> 
> Reviewer:
> Mozilla
> 
> Comments:
> automatic validation
